<script lang="ts">
	import { goto } from '$app/navigation';
	import { invoke } from '@tauri-apps/api/core';

	// [A] stub — real join link generated by control-plane (enrollment token, 15min TTL)
	let joinLink = $state<string | null>(null);
	let loading  = $state(true);
	let copied   = $state(false);

	async function loadJoinLink() {
		try {
			// control-plane returns a short-lived enrollment token URL
			// ankayma://join?token=<signed-jwt>&tenant=<id>
			joinLink = await invoke<string>('create_join_link');
		} catch {
			// Device-link enrollment isn't wired to the control plane yet — don't
			// fabricate a token that looks real. Fall through to the honest
			// "coming soon" state below.
			joinLink = null;
		} finally {
			loading = false;
		}
	}

	loadJoinLink();

	async function copyLink() {
		if (!joinLink) return;
		try {
			await navigator.clipboard.writeText(joinLink);
			copied = true;
			setTimeout(() => (copied = false), 2000);
		} catch {
			// clipboard not available (mobile webview)
		}
	}

	// QR code rendered as SVG — simple data matrix placeholder
	// Real: use a QR library or server-side generated QR image
	let qrPlaceholder = $derived(joinLink ? true : false);
</script>

<main>
	<header>
		<button class="back-btn" onclick={() => goto('/dashboard')}>
			<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<path d="M19 12H5M12 5l-7 7 7 7"/>
			</svg>
		</button>
		<h2>Add a device</h2>
		<div style="width:36px"></div>
	</header>

	<div class="body">
		<p class="desc">Install Ankayma on another device and scan this code, or share the link. The device will join your mesh automatically.</p>

		{#if loading}
			<div class="qr-wrap loading">
				<span class="spinner-lg"></span>
			</div>
		{:else if joinLink}
			<div class="qr-wrap">
				<!-- [A] placeholder — replace with real QR render (qrcode-svg or server endpoint) -->
				<div class="qr-placeholder" aria-label="QR code — scan with Ankayma app">
					<svg width="160" height="160" viewBox="0 0 160 160" fill="none" xmlns="http://www.w3.org/2000/svg">
						<!-- Finder pattern TL -->
						<rect x="10" y="10" width="40" height="40" rx="4" fill="var(--c-accent)" fill-opacity="0.15" stroke="var(--c-accent)" stroke-width="2"/>
						<rect x="18" y="18" width="24" height="24" rx="2" fill="var(--c-accent)"/>
						<!-- Finder pattern TR -->
						<rect x="110" y="10" width="40" height="40" rx="4" fill="var(--c-accent)" fill-opacity="0.15" stroke="var(--c-accent)" stroke-width="2"/>
						<rect x="118" y="18" width="24" height="24" rx="2" fill="var(--c-accent)"/>
						<!-- Finder pattern BL -->
						<rect x="10" y="110" width="40" height="40" rx="4" fill="var(--c-accent)" fill-opacity="0.15" stroke="var(--c-accent)" stroke-width="2"/>
						<rect x="18" y="118" width="24" height="24" rx="2" fill="var(--c-accent)"/>
						<!-- Data area placeholder -->
						<text x="80" y="84" text-anchor="middle" font-size="9" fill="var(--c-text-dim)" font-family="monospace">QR pending</text>
						<text x="80" y="96" text-anchor="middle" font-size="8" fill="var(--c-text-dim)" font-family="monospace">real token</text>
					</svg>
				</div>
				<p class="qr-note">Scan with the Ankayma app · Valid for 15 minutes</p>
			</div>

			<div class="divider"><span>or share the link</span></div>

			<div class="link-box">
				<code class="link-text">{joinLink.slice(0, 42)}…</code>
				<button class="copy-btn" onclick={copyLink}>
					{#if copied}
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--c-success)" stroke-width="2.5">
							<path d="M20 6L9 17l-5-5"/>
						</svg>
					{:else}
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
							<rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
						</svg>
					{/if}
				</button>
			</div>
		{:else}
			<div class="qr-wrap">
				<svg width="120" height="120" viewBox="0 0 24 24" fill="none" stroke="var(--c-accent)" stroke-width="1.5" stroke-opacity="0.6">
					<rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
				</svg>
			</div>
			<p class="qr-note">Device-link enrollment is coming soon.</p>
			<p class="desc">For now, install Ankayma on the other device and sign in with the same GitHub account — it joins your mesh automatically.</p>
		{/if}

		<div class="platforms">
			<p class="platforms-label">Download Ankayma on</p>
			<div class="platform-row">
				<a class="platform-chip" href="https://apps.apple.com" target="_blank" rel="noopener">
					<span>🍎</span> iOS
				</a>
				<a class="platform-chip" href="https://play.google.com" target="_blank" rel="noopener">
					<span>🤖</span> Android
				</a>
				<a class="platform-chip" href="https://github.com/ankayma/open-client/releases" target="_blank" rel="noopener">
					<span>💻</span> Desktop
				</a>
			</div>
		</div>
	</div>
</main>

<style>
	main {
		flex: 1;
		display: flex;
		flex-direction: column;
		padding: calc(var(--safe-top) + 16px) 16px calc(var(--safe-bottom) + 32px);
		max-width: 420px;
		margin: 0 auto;
		width: 100%;
	}

	header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 8px 0;
		margin-bottom: 16px;
	}

	h2 { font-size: 18px; font-weight: 700; }

	.back-btn {
		display: flex;
		align-items: center;
		color: var(--c-text-dim);
		padding: 8px;
		border-radius: 8px;
	}

	.body {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 20px;
	}

	.desc {
		font-size: 14px;
		color: var(--c-text-dim);
		text-align: center;
		line-height: 1.6;
	}

	.qr-wrap {
		width: 200px;
		height: 200px;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: var(--radius);
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 8px;
		padding: 16px;
	}

	.qr-wrap.loading { gap: 0; }

	.qr-placeholder { display: flex; align-items: center; justify-content: center; }

	.qr-note {
		font-size: 11px;
		color: var(--c-text-dim);
		text-align: center;
		line-height: 1.4;
	}

	.spinner-lg {
		width: 32px;
		height: 32px;
		border: 3px solid var(--c-border);
		border-top-color: var(--c-accent);
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	@keyframes spin { to { transform: rotate(360deg); } }

	.divider {
		width: 100%;
		display: flex;
		align-items: center;
		gap: 12px;
		color: var(--c-text-dim);
		font-size: 12px;
	}

	.divider::before, .divider::after {
		content: '';
		flex: 1;
		height: 1px;
		background: var(--c-border);
	}

	.link-box {
		width: 100%;
		display: flex;
		align-items: center;
		gap: 8px;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: var(--radius);
		padding: 12px 14px;
	}

	.link-text {
		flex: 1;
		font-family: 'SF Mono', 'Fira Code', monospace;
		font-size: 12px;
		color: var(--c-text-dim);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.copy-btn {
		flex-shrink: 0;
		width: 32px;
		height: 32px;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 6px;
		background: var(--c-border);
		color: var(--c-text-dim);
		transition: background 0.15s;
	}

	.copy-btn:hover { background: var(--c-accent); color: #fff; }

	.platforms { width: 100%; }

	.platforms-label {
		font-size: 12px;
		color: var(--c-text-dim);
		margin-bottom: 10px;
		text-align: center;
	}

	.platform-row {
		display: flex;
		gap: 8px;
		justify-content: center;
	}

	.platform-chip {
		display: flex;
		align-items: center;
		gap: 6px;
		padding: 8px 14px;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: 8px;
		font-size: 13px;
		color: var(--c-text);
		transition: border-color 0.15s;
	}

	.platform-chip:hover { border-color: var(--c-accent); text-decoration: none; }
</style>
