<script lang="ts">
	import { onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { goto } from '$app/navigation';
	import { joinEnrollNode, createJoinLink } from '$lib/tauri';
	import { pendingInvite } from '$lib/stores';
	import { encodeQR } from '$lib/qr';
	import { runWithStepUp, isStepUpRequired } from '$lib/stepup';

	// Real join link generated by the control plane (single-use enrollment token).
	let joinLink = $state<string | null>(null);
	let loading  = $state(true);
	let copied   = $state(false);

	// Configurable node-invite TTL (server clamps to [1m, 7d]). [A] invite-flow §TTL.
	const NODE_TTL_OPTIONS = [
		{ label: '1 hour',  secs: 3600 },
		{ label: '6 hours', secs: 21600 },
		{ label: '24 hours', secs: 86400 },
		{ label: '7 days',  secs: 604800 },
	];
	let nodeTtl = $state(86400);
	let ttlLabel = $derived(NODE_TTL_OPTIONS.find((o) => o.secs === nodeTtl)?.label ?? '24 hours');

	// QR is rendered dependency-free onto a canvas (so it also exports to PNG).
	let qrCanvas = $state<HTMLCanvasElement | null>(null);
	$effect(() => {
		if (qrCanvas && joinLink) drawQR(qrCanvas, joinLink);
	});

	function drawQR(canvas: HTMLCanvasElement, text: string) {
		const { size, modules } = encodeQR(text);
		const quiet = 4;
		const scale = 5;
		const dim = (size + quiet * 2) * scale;
		canvas.width = dim;
		canvas.height = dim;
		const ctx = canvas.getContext('2d');
		if (!ctx) return;
		ctx.fillStyle = '#ffffff';
		ctx.fillRect(0, 0, dim, dim);
		ctx.fillStyle = '#000000';
		for (let r = 0; r < size; r++) {
			for (let c = 0; c < size; c++) {
				if (modules[r][c]) ctx.fillRect((c + quiet) * scale, (r + quiet) * scale, scale, scale);
			}
		}
	}

	function exportQR() {
		if (!qrCanvas) return;
		const a = document.createElement('a');
		a.download = 'ankayma-invite.png';
		a.href = qrCanvas.toDataURL('image/png');
		a.click();
	}

	// Recipient side: this device redeems a node invite (`ankayma://join?token=…`)
	// to enroll itself into the invite's tenant. Prefilled when we arrived via a
	// deep link. [A] flow per docs/part-d-invite-flow.md (Cases C+D).
	let joinToken    = $state('');
	let joinHostname = $state('');
	let joinBusy     = $state(false);
	let joinError    = $state<string | null>(null);
	let joinDone     = $state(false);

	onMount(() => {
		const invite = get(pendingInvite);
		if (invite?.type === 'join-node') {
			joinToken = invite.token;
			pendingInvite.set(null);
		}
	});

	async function handleJoinEnroll() {
		joinBusy = true;
		joinError = null;
		try {
			// Accept a full ankayma://join?token=… link or a bare token.
			const m = joinToken.match(/token=([^&\s]+)/);
			const tok = m ? m[1] : joinToken.trim();
			await joinEnrollNode(tok, joinHostname.trim());
			joinDone = true;
			setTimeout(() => goto('/dashboard'), 700);
		} catch (e: unknown) {
			joinError = e instanceof Error ? e.message : 'Enrollment failed';
		} finally {
			joinBusy = false;
		}
	}

	// Multi-user tenants gate invite minting behind a step-up. We DON'T pop the OTP
	// modal on page load (that would email a code on mere navigation); instead we
	// detect the gate and show a "Generate invite link" button the admin opts into.
	let needsStepUp = $state(false);

	async function loadJoinLink() {
		loading = true;
		try {
			// control-plane returns a single-use enrollment token URL
			// ankayma://join?token=<token>&tenant=<id>, valid for the chosen TTL.
			joinLink = await createJoinLink(nodeTtl);
			needsStepUp = false;
		} catch (e) {
			if (isStepUpRequired(e)) {
				// Gated — surface an opt-in button rather than auto-minting.
				joinLink = null;
				needsStepUp = true;
			} else {
				// Device-link enrollment isn't wired to the control plane yet — don't
				// fabricate a token that looks real. Fall through to the honest
				// "coming soon" state below.
				joinLink = null;
			}
		} finally {
			loading = false;
		}
	}

	loadJoinLink();

	// Admin opts into the gated mint: run the OTP step-up, then mint with the proof.
	async function generateWithStepUp() {
		try {
			joinLink = await runWithStepUp('enroll_node', (proof) => createJoinLink(nodeTtl, proof));
			needsStepUp = false;
		} catch {
			// cancelled or failed — keep the opt-in button.
		}
	}

	// Re-mint with a fresh TTL when the admin picks a different expiry.
	function onTtlChange() {
		joinLink = null;
		loadJoinLink();
	}

	async function copyLink() {
		if (!joinLink) return;
		try {
			await navigator.clipboard.writeText(joinLink);
			copied = true;
			setTimeout(() => (copied = false), 2000);
		} catch {
			// clipboard not available (mobile webview)
		}
	}
</script>

<main>
	<header>
		<button class="back-btn" onclick={() => goto('/dashboard')}>
			<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<path d="M19 12H5M12 5l-7 7 7 7"/>
			</svg>
		</button>
		<h2>Add a device</h2>
		<div style="width:36px"></div>
	</header>

	<div class="body">
		<section class="join-section">
			<h3>Have an invite link?</h3>
			<p class="join-desc">Enroll <strong>this device</strong> into a team you were invited to. Paste the <code>ankayma://join…</code> link or token.</p>
			{#if joinDone}
				<p class="join-ok">Enrolled — taking you to the dashboard…</p>
			{:else}
				<input
					class="join-input"
					bind:value={joinToken}
					placeholder="ankayma://join?token=…"
					autocapitalize="none"
					autocorrect="off"
					spellcheck="false"
				/>
				<input
					class="join-input"
					bind:value={joinHostname}
					placeholder="Name for this device (optional)"
					autocapitalize="none"
					autocorrect="off"
					spellcheck="false"
				/>
				{#if joinError}<p class="join-err">{joinError}</p>{/if}
				<button
					class="join-btn"
					onclick={handleJoinEnroll}
					disabled={joinBusy || !joinToken.trim()}
				>
					{joinBusy ? 'Connecting…' : 'Join with invite'}
				</button>
			{/if}
		</section>

		<div class="divider"><span>or invite another device</span></div>

		<p class="desc">Install Ankayma on another device and scan this code, or share the link. The device will join your mesh automatically.</p>

		<div class="ttl-row">
			<label for="node-ttl">Link expires in</label>
			<select id="node-ttl" bind:value={nodeTtl} onchange={onTtlChange} disabled={loading}>
				{#each NODE_TTL_OPTIONS as o (o.secs)}
					<option value={o.secs}>{o.label}</option>
				{/each}
			</select>
		</div>

		{#if loading}
			<div class="qr-wrap loading">
				<span class="spinner-lg"></span>
			</div>
		{:else if joinLink}
			<div class="qr-wrap">
				<canvas bind:this={qrCanvas} class="qr-canvas" aria-label="QR code — scan with the Ankayma app"></canvas>
			</div>
			<p class="qr-note">Scan with the Ankayma app · Valid for {ttlLabel}</p>
			<button class="qr-export" onclick={exportQR}>Export QR as PNG</button>

			<div class="divider"><span>or share the link</span></div>

			<div class="link-box">
				<code class="link-text">{joinLink.slice(0, 42)}…</code>
				<button class="copy-btn" onclick={copyLink}>
					{#if copied}
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--c-success)" stroke-width="2.5">
							<path d="M20 6L9 17l-5-5"/>
						</svg>
					{:else}
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
							<rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
						</svg>
					{/if}
				</button>
			</div>
		{:else if needsStepUp}
			<div class="qr-wrap">
				<svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="var(--c-accent)" stroke-width="1.5" stroke-opacity="0.8">
					<rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
				</svg>
			</div>
			<p class="qr-note">This team requires a quick verification before minting an invite.</p>
			<button class="join-btn" onclick={generateWithStepUp}>Verify &amp; generate invite link</button>
		{:else}
			<div class="qr-wrap">
				<svg width="120" height="120" viewBox="0 0 24 24" fill="none" stroke="var(--c-accent)" stroke-width="1.5" stroke-opacity="0.6">
					<rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
				</svg>
			</div>
			<p class="qr-note">Device-link enrollment is coming soon.</p>
			<p class="desc">For now, install Ankayma on the other device and sign in with the same GitHub account — it joins your mesh automatically.</p>
		{/if}

		<div class="platforms">
			<p class="platforms-label">Download Ankayma on</p>
			<div class="platform-row">
				<a class="platform-chip" href="https://apps.apple.com" target="_blank" rel="noopener">
					<span>🍎</span> iOS
				</a>
				<a class="platform-chip" href="https://play.google.com" target="_blank" rel="noopener">
					<span>🤖</span> Android
				</a>
				<a class="platform-chip" href="https://github.com/ankayma/open-client/releases" target="_blank" rel="noopener">
					<span>💻</span> Desktop
				</a>
			</div>
		</div>
	</div>
</main>

<style>
	main {
		flex: 1;
		display: flex;
		flex-direction: column;
		padding: calc(var(--safe-top) + 16px) 16px calc(var(--safe-bottom) + 32px);
		max-width: 420px;
		margin: 0 auto;
		width: 100%;
	}

	header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 8px 0;
		margin-bottom: 16px;
	}

	h2 { font-size: 18px; font-weight: 700; }

	.back-btn {
		display: flex;
		align-items: center;
		color: var(--c-text-dim);
		padding: 8px;
		border-radius: 8px;
	}

	.body {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 20px;
	}

	.desc {
		font-size: 14px;
		color: var(--c-text-dim);
		text-align: center;
		line-height: 1.6;
	}

	.qr-wrap {
		width: 200px;
		height: 200px;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: var(--radius);
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 8px;
		padding: 16px;
	}

	.qr-wrap.loading { gap: 0; }

	.qr-canvas {
		width: 168px;
		height: 168px;
		image-rendering: pixelated;
		border-radius: 4px;
	}

	.ttl-row {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		font-size: 13px;
		color: var(--c-text-dim);
	}

	.ttl-row select {
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: 8px;
		padding: 7px 10px;
		color: var(--c-text);
		font-size: 13px;
	}

	.qr-export {
		font-size: 12px;
		color: var(--c-text-dim);
		padding: 6px 12px;
		border: 1px solid var(--c-border);
		border-radius: 8px;
		background: var(--c-surface);
	}

	.qr-export:hover { border-color: var(--c-accent); color: var(--c-text); }

	.qr-note {
		font-size: 11px;
		color: var(--c-text-dim);
		text-align: center;
		line-height: 1.4;
	}

	.spinner-lg {
		width: 32px;
		height: 32px;
		border: 3px solid var(--c-border);
		border-top-color: var(--c-accent);
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	@keyframes spin { to { transform: rotate(360deg); } }

	.divider {
		width: 100%;
		display: flex;
		align-items: center;
		gap: 12px;
		color: var(--c-text-dim);
		font-size: 12px;
	}

	.divider::before, .divider::after {
		content: '';
		flex: 1;
		height: 1px;
		background: var(--c-border);
	}

	.link-box {
		width: 100%;
		display: flex;
		align-items: center;
		gap: 8px;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: var(--radius);
		padding: 12px 14px;
	}

	.link-text {
		flex: 1;
		font-family: 'SF Mono', 'Fira Code', monospace;
		font-size: 12px;
		color: var(--c-text-dim);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.copy-btn {
		flex-shrink: 0;
		width: 32px;
		height: 32px;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 6px;
		background: var(--c-border);
		color: var(--c-text-dim);
		transition: background 0.15s;
	}

	.copy-btn:hover { background: var(--c-accent); color: #fff; }

	.platforms { width: 100%; }

	.platforms-label {
		font-size: 12px;
		color: var(--c-text-dim);
		margin-bottom: 10px;
		text-align: center;
	}

	.platform-row {
		display: flex;
		gap: 8px;
		justify-content: center;
	}

	.platform-chip {
		display: flex;
		align-items: center;
		gap: 6px;
		padding: 8px 14px;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: 8px;
		font-size: 13px;
		color: var(--c-text);
		transition: border-color 0.15s;
	}

	.platform-chip:hover { border-color: var(--c-accent); text-decoration: none; }

	/* Recipient (join-via-invite) section */
	.join-section {
		width: 100%;
		background: var(--c-surface);
		border: 1px solid var(--c-border);
		border-radius: var(--radius);
		padding: 16px;
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	.join-section h3 { font-size: 15px; font-weight: 700; }

	.join-desc {
		font-size: 13px;
		color: var(--c-text-dim);
		line-height: 1.5;
	}

	.join-desc code {
		font-family: 'SF Mono', 'Fira Code', monospace;
		font-size: 12px;
		color: var(--c-accent);
	}

	.join-input {
		width: 100%;
		background: var(--c-bg);
		border: 1px solid var(--c-border);
		border-radius: 8px;
		padding: 10px 12px;
		color: var(--c-text);
		font-size: 13px;
	}

	.join-btn {
		background: var(--c-accent);
		color: #fff;
		font-weight: 600;
		font-size: 14px;
		padding: 10px 16px;
		border-radius: 9px;
	}

	.join-btn:disabled { opacity: 0.5; }

	.join-err { color: var(--c-danger); font-size: 13px; }

	.join-ok { color: var(--c-success); font-size: 14px; font-weight: 600; }
</style>
