#!/usr/bin/env bash
# scripts/android-sdk36-patch.sh
#
# Raise compileSdk/targetSdk in the Gradle project generated by `cargo tauri android init`.
#
# WHY A SCRIPT: gen/android is regenerated scaffolding and git-ignored, so it cannot be
# edited by hand — it has to be patched after every init. Same mechanism as
# scripts/android-postinit.sh (adaptive-icon safe-zone fix).
#
# WHY 36: Google Play requires new apps and updates to target Android 16 (API 36) from
# 2026-08-31. The Tauri template defaults lower, so Play would reject the upload.
#
# NOTE: this raises the target for BOTH distribution lanes — the APK published to
# get.ankayma.com is the same build as the bundle sent to Play. API 35+ enforces
# edge-to-edge layout, so re-test the app on a real device (system bar overlap, VpnService
# behaviour) after changing this, not only that it compiles.
#
# Run AFTER android-postinit.sh and BEFORE `cargo tauri android build`.
#
# [A — UNVERIFIED] This script has never run for real. Assumptions to check:
#   1. the path to build.gradle.kts in the Tauri 2 template
#   2. compileSdk/targetSdk declared as literals (`compileSdk = 34`) rather than variables
#   3. whether the template's AGP version supports compileSdk 36
# If it fails, read the Gradle config it prints below to see what needs adjusting.

set -euo pipefail

TARGET_SDK="${ANDROID_TARGET_SDK:-36}"
COMPILE_SDK="${ANDROID_COMPILE_SDK:-36}"

# Tauri 2 generates the project into gui/src-tauri/gen/android/
GEN_ROOT="gui/src-tauri/gen/android"
APP_GRADLE="${GEN_ROOT}/app/build.gradle.kts"
ROOT_GRADLE="${GEN_ROOT}/build.gradle.kts"

echo "→ Patching Gradle to compileSdk=${COMPILE_SDK} / targetSdk=${TARGET_SDK}"

if [ ! -f "$APP_GRADLE" ]; then
  echo "✗ Not found: $APP_GRADLE" >&2
  echo "  Current gen/android tree:" >&2
  find "$GEN_ROOT" -name 'build.gradle*' 2>/dev/null >&2 || echo "  (gen/android does not exist)" >&2
  exit 1
fi

echo "--- BEFORE ---"
grep -nE 'compileSdk|targetSdk|minSdk' "$APP_GRADLE" || true

# In-place edit, portable across GNU and BSD sed.
#
# `sed -i -E` is NOT portable: GNU sed treats -i as "no backup suffix", while BSD sed
# (macOS) reads the NEXT argument as the suffix and would silently consume -E. This
# matters because Android builds are also produced locally on macOS, not only in CI.
# Writing to a temp file and moving it back behaves identically everywhere.
TMP_GRADLE="$(mktemp)"
sed -E \
  -e "s/(compileSdk(Version)?[[:space:]]*=?[[:space:]]*)[0-9]+/\1${COMPILE_SDK}/" \
  -e "s/(targetSdk(Version)?[[:space:]]*=?[[:space:]]*)[0-9]+/\1${TARGET_SDK}/" \
  "$APP_GRADLE" > "$TMP_GRADLE"
mv "$TMP_GRADLE" "$APP_GRADLE"

echo "--- AFTER ---"
grep -nE 'compileSdk|targetSdk|minSdk' "$APP_GRADLE" || true

# sed does not fail when nothing matches, so verify the substitution actually happened.
if ! grep -qE "compileSdk(Version)?[[:space:]]*=?[[:space:]]*${COMPILE_SDK}" "$APP_GRADLE"; then
  echo "✗ compileSdk was not set to ${COMPILE_SDK}." >&2
  echo "  The template most likely declares it through a variable" >&2
  echo "  (libs.versions.toml / gradle.properties) rather than a literal. android{} block:" >&2
  sed -n '/^android[[:space:]]*{/,/^}/p' "$APP_GRADLE" >&2
  exit 1
fi

if ! grep -qE "targetSdk(Version)?[[:space:]]*=?[[:space:]]*${TARGET_SDK}" "$APP_GRADLE"; then
  echo "✗ targetSdk was not set to ${TARGET_SDK}. See the android{} block above." >&2
  exit 1
fi

echo "  ✓ compileSdk/targetSdk = ${COMPILE_SDK}/${TARGET_SDK}"

# ---------------------------------------------------------------------------
# AGP version — reported only, never changed automatically.
# ---------------------------------------------------------------------------
# compileSdk 36 needs a recent enough AGP. If the build fails with
#   "compileSdk 36 requires Android Gradle plugin X or higher"
# bump AGP in the file below, and consider moving the workflow from JDK 17 to JDK 21
# (AGP 9.x requires it). Not automated: an AGP bump can bring breaking Gradle DSL
# changes, which needs a human to look at.
if [ -f "$ROOT_GRADLE" ]; then
  echo "→ Current AGP version (for reference):"
  grep -nE 'com\.android\.(application|tools\.build)|agp' "$ROOT_GRADLE" || echo "  (no AGP declaration found at root)"
fi

for f in "${GEN_ROOT}/gradle/libs.versions.toml" "${GEN_ROOT}/gradle.properties"; do
  [ -f "$f" ] && { echo "→ $f:"; grep -nE 'agp|android|sdk' "$f" || true; }
done

echo "✓ android-sdk36-patch.sh done"
