#!/usr/bin/env bash
# ios-postinit.sh — apply the Ankayma Packet Tunnel extension to the cargo-mobile2
# generated iOS project. The generated project lives in gui/src-tauri/gen/apple
# (gitignored, regenerated by `cargo tauri ios init`), so our customisation is kept
# in source-controlled gui/src-tauri/ios/ and re-applied here. Run AFTER
# `cargo tauri ios init` and BEFORE building. Idempotent. [T:A.1.9]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)" # client/ (workspace root)
GEN="$ROOT/gui/src-tauri/gen/apple"
IOS="$ROOT/gui/src-tauri/ios"
PROJ="$GEN/project.yml"

if [ ! -f "$PROJ" ]; then
  echo "✗ $PROJ not found — run 'cd gui/src-tauri && cargo tauri ios init' first." >&2
  exit 1
fi

# Patch project.yml (idempotent — skip if the extension target is already there).
# NOTE: xcodegen *generates* entitlements files from the `entitlements.properties`
# in project.yml (a bare `path:` is rewritten to an empty dict), so the app's NE +
# App Group entitlements are injected as properties here rather than copied as a
# file — a copied file would be overwritten on the next `xcodegen generate`.
if grep -q "ankayma-gui_PacketTunnel" "$PROJ"; then
  echo "• extension target already present — skipping project.yml patch"
else
  # Two inserts on the APP target (done before appending the extension, which has its
  # own `dependencies:`/`entitlements:` blocks): embed the extension, and give the
  # app the NE + App Group entitlements.
  awk '
    { print }
    /^    dependencies:$/ && !dep {
      print "      - target: ankayma-gui_PacketTunnel"; dep=1
    }
    /^      path: ankayma-gui_iOS\/ankayma-gui_iOS\.entitlements$/ && !ent {
      print "      properties:";
      print "        com.apple.developer.networking.networkextension:";
      print "          - packet-tunnel-provider";
      print "        com.apple.security.application-groups:";
      print "          - group.com.ankayma.app";
      ent=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  # Append the extension target spec under `targets:` (the last key in the file).
  cat "$IOS/PacketTunnel.target.yml" >>"$PROJ"
  echo "✓ project.yml patched (extension target + app embed + entitlements)"
fi

# 3. Regenerate the .xcodeproj from the patched project.yml.
(cd "$GEN" && xcodegen generate)
echo "✓ xcodegen done — gen/apple/ankayma-gui.xcodeproj (app + PacketTunnel targets)"
