#!/usr/bin/env bash
# ios-postinit.sh — apply the Ankayma Packet Tunnel extension to the cargo-mobile2
# generated iOS project. The generated project lives in gui/src-tauri/gen/apple
# (gitignored, regenerated by `cargo tauri ios init`), so our customisation is kept
# in source-controlled gui/src-tauri/ios/ and re-applied here. Run AFTER
# `cargo tauri ios init` and BEFORE building. Idempotent. [T:A.1.9]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)" # client/ (workspace root)
GEN="$ROOT/gui/src-tauri/gen/apple"
IOS="$ROOT/gui/src-tauri/ios"
PROJ="$GEN/project.yml"

if [ ! -f "$PROJ" ]; then
  echo "✗ $PROJ not found — run 'cd gui/src-tauri && cargo tauri ios init' first." >&2
  exit 1
fi

# Patch project.yml (idempotent — skip if the extension target is already there).
# NOTE: xcodegen *generates* entitlements files from the `entitlements.properties`
# in project.yml (a bare `path:` is rewritten to an empty dict), so the app's NE +
# App Group entitlements are injected as properties here rather than copied as a
# file — a copied file would be overwritten on the next `xcodegen generate`.
if grep -q "ankayma-gui_PacketTunnel" "$PROJ"; then
  echo "• extension target already present — skipping project.yml patch"
else
  # Two inserts on the APP target (done before appending the extension, which has its
  # own `dependencies:`/`entitlements:` blocks): embed the extension, and give the
  # app the NE + App Group entitlements.
  awk '
    { print }
    /^      - path: ankayma-gui_iOS$/ && !src {
      print "      - path: ../../ios/AppSupport"; src=1
    }
    /^    dependencies:$/ && !dep {
      print "      - target: ankayma-gui_PacketTunnel"; dep=1
    }
    /^      path: ankayma-gui_iOS\/ankayma-gui_iOS\.entitlements$/ && !ent {
      print "      properties:";
      print "        com.apple.developer.networking.networkextension:";
      print "          - packet-tunnel-provider";
      print "        com.apple.security.application-groups:";
      print "          - group.com.ankayma.app";
      ent=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  # Append the extension target spec under `targets:` (the last key in the file).
  cat "$IOS/PacketTunnel.target.yml" >>"$PROJ"
  echo "✓ project.yml patched (extension target + app embed + entitlements)"
fi

# 3. Camera usage string for the in-app QR scanner (barcode-scanner plugin).
#    App Store rejects a camera-using app without NSCameraUsageDescription (ASC
#    error 90683). The app Info.plist is GENERATED by xcodegen from project.yml
#    `info.properties`, so the key MUST go there — editing the generated plist gets
#    wiped on the next `xcodegen generate`. Inject into the APP target's info block
#    (anchor on its Info.plist path so we don't touch the extension). Idempotent,
#    ungated (runs even when the extension patch above was skipped). [T:A.1.21]
if ! grep -q "NSCameraUsageDescription" "$PROJ"; then
  awk '
    { print }
    /^      path: ankayma-gui_iOS\/Info\.plist$/ { app_info=1 }
    app_info && /^      properties:$/ && !done {
      print "        NSCameraUsageDescription: Ankayma uses the camera to scan a mesh invite QR code so this device can join your mesh."
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ NSCameraUsageDescription injected into project.yml (app info properties)"
fi

# 3b. Register the ankayma:// custom URL scheme so deep links (invite emails, QR codes,
#     the cp.ankayma.com/join landing page) actually open the app. Without CFBundleURLTypes
#     iOS knows no app handles ankayma:// → Safari shows "the address is invalid" and the
#     link never reaches the app. Same xcodegen-wipes-the-plist reason as the camera key,
#     so it MUST live in project.yml. `cargo tauri ios init` does NOT inject it (a re-init
#     dropped it and broke every deep link). [T:tauri.conf.json plugins.deep-link scheme]
if ! grep -q "CFBundleURLTypes" "$PROJ"; then
  awk '
    { print }
    /^      path: ankayma-gui_iOS\/Info\.plist$/ { app_info=1 }
    app_info && /^      properties:$/ && !done {
      print "        CFBundleURLTypes:"
      print "          - CFBundleURLName: com.ankayma.app"
      print "            CFBundleURLSchemes: [ankayma]"
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ CFBundleURLTypes (ankayma:// scheme) injected into project.yml — deep links open the app"
fi

# 4. Regenerate the .xcodeproj from the patched project.yml.
(cd "$GEN" && xcodegen generate)
echo "✓ xcodegen done — gen/apple/ankayma-gui.xcodeproj (app + PacketTunnel targets)"

# 5. Regenerate the App Icon from the CANONICAL source. `cargo tauri ios init` seeds
#    gen/apple/Assets.xcassets/AppIcon from stale derived icons — it has shipped the
#    WRONG swirl logo to the App Store before (0.1.0, 1.1.3-build1; see memory
#    ios-build-steps). `cargo tauri icon` overwrites the AppIcon set from the "An"
#    canonical icon_source.png. ALWAYS from icons/icon_source.png, never an external file.
export PATH="$HOME/.cargo/bin:$PATH"
(cd "$ROOT/gui/src-tauri" && cargo tauri icon icons/icon_source.png >/dev/null)
echo "✓ app icons regenerated from icons/icon_source.png (canonical 'An') — prevents swirl regression"
