#!/usr/bin/env bash
# ios-postinit.sh — apply the Ankayma Packet Tunnel extension to the cargo-mobile2
# generated iOS project. The generated project lives in gui/src-tauri/gen/apple
# (gitignored, regenerated by `cargo tauri ios init`), so our customisation is kept
# in source-controlled gui/src-tauri/ios/ and re-applied here. Run AFTER
# `cargo tauri ios init` and BEFORE building. Idempotent. [T:A.1.9]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)" # client/ (workspace root)
GEN="$ROOT/gui/src-tauri/gen/apple"
IOS="$ROOT/gui/src-tauri/ios"
PROJ="$GEN/project.yml"

if [ ! -f "$PROJ" ]; then
  echo "✗ $PROJ not found — run 'cd gui/src-tauri && cargo tauri ios init' first." >&2
  exit 1
fi

# Patch project.yml (idempotent — skip if the extension target is already there).
# NOTE: xcodegen *generates* entitlements files from the `entitlements.properties`
# in project.yml (a bare `path:` is rewritten to an empty dict), so the app's NE +
# App Group entitlements are injected as properties here rather than copied as a
# file — a copied file would be overwritten on the next `xcodegen generate`.
if grep -q "ankayma-gui_PacketTunnel" "$PROJ"; then
  echo "• extension target already present — skipping project.yml patch"
else
  # Two inserts on the APP target (done before appending the extension, which has its
  # own `dependencies:`/`entitlements:` blocks): embed the extension, and give the
  # app the NE + App Group entitlements.
  awk '
    { print }
    /^      - path: ankayma-gui_iOS$/ && !src {
      print "      - path: ../../ios/AppSupport"; src=1
    }
    /^    dependencies:$/ && !dep {
      print "      - target: ankayma-gui_PacketTunnel"; dep=1
    }
    /^      path: ankayma-gui_iOS\/ankayma-gui_iOS\.entitlements$/ && !ent {
      print "      properties:";
      print "        com.apple.developer.networking.networkextension:";
      print "          - packet-tunnel-provider";
      print "        com.apple.security.application-groups:";
      print "          - group.com.ankayma.app";
      ent=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  # Append the extension target spec under `targets:` (the last key in the file).
  cat "$IOS/PacketTunnel.target.yml" >>"$PROJ"
  echo "✓ project.yml patched (extension target + app embed + entitlements)"
fi

# 3. Camera usage string for the in-app QR scanner (barcode-scanner plugin).
#    App Store rejects a camera-using app without NSCameraUsageDescription (ASC
#    error 90683). The app Info.plist is GENERATED by xcodegen from project.yml
#    `info.properties`, so the key MUST go there — editing the generated plist gets
#    wiped on the next `xcodegen generate`. Inject into the APP target's info block
#    (anchor on its Info.plist path so we don't touch the extension). Idempotent,
#    ungated (runs even when the extension patch above was skipped). [T:A.1.21]
if ! grep -q "NSCameraUsageDescription" "$PROJ"; then
  awk '
    { print }
    /^      path: ankayma-gui_iOS\/Info\.plist$/ { app_info=1 }
    app_info && /^      properties:$/ && !done {
      print "        NSCameraUsageDescription: Ankayma uses the camera to scan a mesh invite QR code so this device can join your mesh."
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ NSCameraUsageDescription injected into project.yml (app info properties)"
fi

# 3b. Register the ankayma:// custom URL scheme so deep links (invite emails, QR codes,
#     the cp.ankayma.com/join landing page) actually open the app. Without CFBundleURLTypes
#     iOS knows no app handles ankayma:// → Safari shows "the address is invalid" and the
#     link never reaches the app. Same xcodegen-wipes-the-plist reason as the camera key,
#     so it MUST live in project.yml. `cargo tauri ios init` does NOT inject it (a re-init
#     dropped it and broke every deep link). [T:tauri.conf.json plugins.deep-link scheme]
if ! grep -q "CFBundleURLTypes" "$PROJ"; then
  awk '
    { print }
    /^      path: ankayma-gui_iOS\/Info\.plist$/ { app_info=1 }
    app_info && /^      properties:$/ && !done {
      print "        CFBundleURLTypes:"
      print "          - CFBundleURLName: com.ankayma.app"
      print "            CFBundleURLSchemes: [ankayma]"
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ CFBundleURLTypes (ankayma:// scheme) injected into project.yml — deep links open the app"
fi

# 3c. Associated Domains — WKWebView refuses navigator.credentials.create()/get()
#     (WebAuthn security-key step-up, E-7 Phase 3) unless the app claims webcredentials:
#     for our RP ID (WEBAUTHN_RP_ID=ankayma.com). Same xcodegen-regenerates-the-file
#     reason as the NE/App Group keys above, so it MUST be an entitlements *property*
#     here — editing the generated .entitlements gets wiped. Only the APP target needs
#     it; the PacketTunnel extension does not. Idempotent, ungated.
#     Depends on two things outside this repo, both required or the App Store profile
#     will not carry the entitlement and Archive fails "profile doesn't include…":
#       - Associated Domains enabled on App ID com.ankayma.app in the developer portal
#       - AASA served at https://ankayma.com/.well-known/apple-app-site-association
#         declaring 8UF87JS6WW.com.ankayma.app under "webcredentials" (live 2026-07-29)
#     [T:developer.apple.com/documentation/xcode/supporting-associated-domains]
if ! grep -q "associated-domains" "$PROJ"; then
  awk '
    { print }
    /^      path: ankayma-gui_iOS\/ankayma-gui_iOS\.entitlements$/ { app_ent=1 }
    app_ent && /^      properties:$/ && !done {
      print "        com.apple.developer.associated-domains:"
      print "          - webcredentials:ankayma.com"
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ associated-domains (webcredentials:ankayma.com) injected into project.yml — WebAuthn in WKWebView"
fi

# 3f. Link AuthenticationServices + LocalAuthentication into the APP target.
#     Cargo emits the objc2 crates' link directives when it builds the binary itself, as
#     on macOS — but on iOS the final link is Xcode's, and it never sees them, because
#     they do not survive into the Rust staticlib. The native security-key ceremony
#     references three C globals (…DescriptorTransportUSB/NFC/Bluetooth), so without this
#     the app fails to link with "Undefined symbols for architecture arm64". Caught by the
#     first real iOS build, not by `cargo check --target aarch64-apple-ios`, which never
#     links. LocalAuthentication is listed for the same reason should the Face ID factor
#     ever reference a symbol rather than looking the class up at runtime.
#     The APP target's `dependencies:` is the FIRST one in the generated file; the
#     extension's comes later and must not be touched. [T — reproduced 2026-07-30]
if ! grep -q "AuthenticationServices.framework" "$PROJ"; then
  awk '
    { print }
    /^    dependencies:$/ && !done {
      print "      - sdk: AuthenticationServices.framework"
      print "      - sdk: LocalAuthentication.framework"
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ AuthenticationServices + LocalAuthentication linked into the app target"
fi

# 3e. Face ID usage string for the E-7 step-up factor (Secure Enclave key gated by
#     biometryCurrentSet — same code as macOS Touch ID, see gui/src-tauri/src/lib.rs
#     platform_key_enroll). iOS does NOT return an error when this key is missing: it
#     TERMINATES the app the moment Face ID is invoked, so shipping without it turns the
#     first step-up into a crash. Touch ID devices need no equivalent key. Same
#     xcodegen-wipes-the-plist reason as the camera key, so it lives in project.yml.
#     [T:developer.apple.com/documentation/bundleresources/information_property_list/nsfaceidusagedescription]
if ! grep -q "NSFaceIDUsageDescription" "$PROJ"; then
  awk '
    { print }
    /^      path: ankayma-gui_iOS\/Info\.plist$/ { app_info=1 }
    app_info && /^      properties:$/ && !done {
      print "        NSFaceIDUsageDescription: Ankayma uses Face ID to confirm sensitive actions, such as adding a device or changing who can reach your mesh."
      done=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ NSFaceIDUsageDescription injected into project.yml (Face ID step-up would crash without it)"
fi

# 3d. Keep the app's own Rust static lib (libapp.a) OUT of the app bundle. The app
#     target globs `- path: Externals` as sources and tauri writes libapp.a there, so
#     xcodegen adds it to BOTH "Link Binary" (correct) AND "Copy Bundle Resources"
#     (wrong) → App Store rejects with 90171 "Invalid bundle structure … libapp.a not
#     permitted". Fix like the PTP staticlib: link via `-lapp` + LIBRARY_SEARCH_PATHS
#     (already set to Externals/<arch>/<config>) and EXCLUDE *.a from the source glob so
#     it is no longer bundled. init drops this; a re-init reintroduced the bug.
if ! grep -q 'OTHER_LDFLAGS.*-lapp' "$PROJ"; then
  awk '
    { print }
    /^      - path: Externals$/ && !ex {
      print "        excludes:"
      print "          - \"**/*.a\""
      ex=1
    }
    /^        LIBRARY_SEARCH_PATHS\[arch=arm64\]:/ && !ld {
      print "        OTHER_LDFLAGS: $(inherited) -lapp"
      ld=1
    }
  ' "$PROJ" >"$PROJ.tmp" && mv "$PROJ.tmp" "$PROJ"
  echo "✓ libapp.a linked via -lapp + excluded from bundle (fixes App Store 90171)"
fi

# 4. Regenerate the .xcodeproj from the patched project.yml.
(cd "$GEN" && xcodegen generate)
echo "✓ xcodegen done — gen/apple/ankayma-gui.xcodeproj (app + PacketTunnel targets)"

# 4b. Drop raw `${FORCE_COLOR}` from the Build Rust Code script. cargo-mobile emits
#     `… ${FORCE_COLOR} ${ARCHS:?}`; when FORCE_COLOR=0/1 (common), clap treats the digit
#     as a positional ARCH → "Arch … isn't a known arch". Flag is optional; omit it.
#     Must re-run xcodegen after patching project.yml. Idempotent.
if grep -q '\${FORCE_COLOR}' "$PROJ"; then
  python3 - "$PROJ" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
text = p.read_text()
old = " ${FORCE_COLOR} ${ARCHS:?}"
new = " ${ARCHS:?}"
if old not in text:
    raise SystemExit(0)
p.write_text(text.replace(old, new, 1))
print("patched FORCE_COLOR out of xcode-script line")
PY
  (cd "$GEN" && xcodegen generate)
  echo "✓ Build Rust Code script: removed FORCE_COLOR digit-as-ARCH bug"
fi

# 5. Regenerate the App Icon from the CANONICAL source. `cargo tauri ios init` seeds
#    gen/apple/Assets.xcassets/AppIcon from stale derived icons — it has shipped the
#    WRONG swirl logo to the App Store before (0.1.0, 1.1.3-build1; see memory
#    ios-build-steps). `cargo tauri icon` overwrites the AppIcon set from the "An"
#    canonical icon_source.png. ALWAYS from icons/icon_source.png, never an external file.
export PATH="$HOME/.cargo/bin:$PATH"
(cd "$ROOT/gui/src-tauri" && cargo tauri icon icons/icon_source.png >/dev/null)
# `cargo tauri icon` ALSO rewrites the committed `icons/` set (same 'An', but a fresh
# non-deterministic encoding each run) → a noisy `icon.icns` M on every build. We only
# needed the git-IGNORED gen/apple AppIcon refreshed (done above); restore the tracked
# source icons so a build never dirties the working tree. (To change the brand, run
# `cargo tauri icon` manually and commit `icons/` — that's a deliberate act, not a build.)
git -C "$ROOT" checkout -- gui/src-tauri/icons/ 2>/dev/null || true
echo "✓ app icons regenerated from icons/icon_source.png (canonical 'An') — prevents swirl regression"
